zookeeper:
  image: mesoscloud/zookeeper:3.4.6-centos-7
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
  environment:
    SERVERS: 'server.1=127.0.0.1'
    MYID: '1'

mesosmaster:
  image: mesosphere/mesos-master:0.26.0-0.2.145.ubuntu1404
  net: host
  volumes:
    - /var/log/mesos/master
  environment:
    MESOS_ZK: 'zk://localhost:2181/mesos'
    MESOS_QUORUM: '1'
    MESOS_CLUSTER: 'local'
    MESOS_HOSTNAME: 'localhost'
    MESOS_LOG_DIR: '/var/log/mesos/master'

mesosslave:
  build: mesos-slave
  net: host
  privileged: true
  volumes:
    - /var/log/mesos/slave
    - /sys:/sys
# /cgroup is needed on some older Linux versions
#    - /cgroup:/cgroup
# /usr/bin/docker is needed if you're running an older docker version
#    - /usr/local/bin/docker:/usr/bin/docker:r
    - /var/run/docker.sock:/var/run/docker.sock:rw
  environment:
    MESOS_MASTER: 'zk://localhost:2181/mesos'
    MESOS_PORT: '5051'
    MESOS_LOG_DIR: '/var/log/mesos/slave'
    MESOS_CONTAINERIZERS: 'docker,mesos'
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
    MESOS_EXECUTOR_SHUTDOWN_GRACE_PERIOD: '90secs'
    MESOS_DOCKER_STOP_TIMEOUT: '60secs'
    MESOS_SWITCH_USER: 'false'
    MESOS_HOSTNAME_LOOKUP: 'false'
# If your workstation doesn't have a resolvable hostname/FQDN then $MESOS_HOSTNAME needs to be set to the host's internal IP-address
    # MESOS_HOSTNAME: $MESOS_HOSTNAME
    # export MESOS_HOSTNAME=10.211.55.3

db:
  build: rec-db
  ports:
   - "27017:27017"

admin:
  image: visenze/weardex-recognition-admin:latest
  ports:
   - "8097:8097"
  net: host
  environment:
    MONGO: '10.211.55.3:27017'
    ZK: '10.211.55.3:2181'

front:
  image: visenze/weardex-recognition-front:latest
  ports:
   - "8082:8082"
  environment:
    MONGO: '10.211.55.3:27017'
    ZK: '10.211.55.3:2181'
  links:
   - zookeeper:rec_zookeeper
   - db:rec_db

router:
  image: visenze/weardex-recognition-router:latest
  ports:
   - "8083:8083"
  net: host
  environment:
    MONGO: '10.211.55.3:27017'
    ZK: '10.211.55.3:2181'
  # links:
  #  - zookeeper:rec_zookeeper
  #  - db:rec_db